POST http://localhost:4000/api/users/register
Content-Type: application/json
Accept: application/json

{
    "username": "Ernesto",
    "email": "ernesto@ernesto.com",
    "password": "ernesto",
    "passwordConfirmation": "ernesto"
}
